import React from 'react'
import styles from '../styles/Home.module.css'
import Head from 'next/head'

const Home = props => {
    return (<div className={styles.container}>
        <Head>
            <title>Home</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
            <h2 style={{color:'white'}}>Home Page</h2>
        </main>
    </div>
    )
}

Home.propTypes = {}

export default Home